"Area: Docker":
  - changed-files:
      - any-glob-to-any-file: ["docker/**"]

"Area: Api":
  - changed-files:
      - any-glob-to-any-file: ["apps/api/**"]

"Area: Web":
  - changed-files:
      - any-glob-to-any-file: ["apps/web/**"]

"Area: Email":
  - changed-files:
      - any-glob-to-any-file: ["packages/email/**"]

"Area: Core":
  - changed-files:
      - any-glob-to-any-file: ["packages/core/**"]

"Area: Docs":
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "**/README.*"
          - "**/CONTRIBUTING.*"
