packages:
  - apps/*
  - packages/*

catalog:
  '@types/bun': ^1.3.2
  tsdown: ^0.15.12
  zod: ^4.1.12

catalogs:
  react:
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.0
    react: ^19.2.0
    react-dom: ^19.2.0
  ts:
    typescript: ^5.9.3

overrides:
  '@types/react': catalog:react
  '@types/react-dom': catalog:react
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  glob@>=10.3.7 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  react: catalog:react
  react-dom: catalog:react
  tmp@<=0.2.3: '>=0.2.4'
  typescript: catalog:ts
